import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsappFloating from "@/components/WhatsappFloating";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title:
    "Future Star | Manufacturing Company in Sialkot, Pakistan | Soccer Kit in Sialkot",
  description: "Generated by create next app",

  // ✅ Favicons (browser will auto-pick best size)
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-48x48.png", sizes: "48x48", type: "image/png" },

      // ✅ Optional fallback (put /public/favicon.ico)
      { url: "/favicon.ico" },
    ],

    // ✅ iOS Home Screen icon (recommended: 180x180)
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },

  // ✅ Optional but recommended (put /public/site.webmanifest)
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-white text-black`}
      >
        <Navbar />
        {children}
        <WhatsappFloating />
        <Footer />
      </body>
    </html>
  );
}
